%% 
{
    "theme" : "light",
    "gitGraph" : {
        "mainBranchName"  : "kkk",
        "mainBranchOrder" : 0
    }
}



gitGraph
    commit id: "DBS-1"
    commit id: "DBS-2"
    branch "Bookman 1 (6502)"
    commit id: "440 / 445"
    checkout "Digital Book System (6502)"
    commit id: "DBS-2D"
    checkout "Bookman 1 (6502)"
    commit id: "640"
    commit id: "1640"
    branch "BKMN"
    commit id: "WP-230B" tag: "Typewriters" type: HIGHLIGHT
    commit id: "WP-335B"
    commit id: "PN-8700MDS" tag: "Word Processors" type: HIGHLIGHT
    commit id: "PN-8800FXB"
    checkout "Bookman 1 (6502)"
    commit id: "840"
    commit id: "561, 563, 565"
    commit id: "560"
    commit id: "580"
    commit id: "761, 763, 765"
    commit id: "770"
    commit id: "1770" tag: "Medical Book System" type: HIGHLIGHT
    branch "Bookman 2 (ES1, SNK8?)"
    commit id: "1440"
    commit id: "590, 1590, 1595"
    commit id: "1840"
    commit id: "BW-10" tag: "Bookman Writer" type: HIGHLIGHT
    branch "Bookman 3 (SNK24, SNK32?)"
    commit id: "787" tag: "Desktop only"
    commit id: "1450"
    commit id: "1470"
    commit id: "1660"
    commit id: "1680"
    commit id: "1850"
    commit id: "1860"
    commit id: "1870 / 1875"
    