const OFFSET_FUNCTION_KEY_1_NAME = 0xAA;
const OFFSET_FUNCTION_KEY_2_NAME = 0xAC;
const OFFSET_FUNCTION_KEY_3_NAME = 0xAE;
const OFFSET_FUNCTION_KEY_4_NAME = 0xB0;


const OFFSET_CARD_ICON_STRUCT = 0x7E;
const CARD_ICON_STRUCT_SIZE = 10; // bytes

module.exports = {
    OFFSET_CARD_ICON_STRUCT,

    OFFSET_FUNCTION_KEY_1_NAME,
    OFFSET_FUNCTION_KEY_2_NAME,
    OFFSET_FUNCTION_KEY_3_NAME,
    OFFSET_FUNCTION_KEY_4_NAME,

    CARD_ICON_STRUCT_SIZE,
};