const OFFSET_FUNCTION_KEY_NAMES = 0xAA;

const OFFSET_CARD_ICON_STRUCT = 0x7E;
const CARD_ICON_STRUCT_SIZE = 10; // bytes

module.exports = {
    OFFSET_CARD_ICON_STRUCT,
    OFFSET_FUNCTION_KEY_NAMES,

    CARD_ICON_STRUCT_SIZE,
};